name: CI Pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

      - name: Log in to Private Docker Registry
        run: |
          echo "${{ secrets.PRIVATE_REGISTRY_PASSWORD }}" | docker login myprivateregistry.com -u "${{ secrets.PRIVATE_REGISTRY_USERNAME }}" --password-stdin

      - name: Push Docker image to Private Docker Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/flask-app:latest myprivateregistry.com/myprivateregistry/flask-app:latest
          docker push myprivateregistry.com/myprivateregistry/flask-app:latest 
